name: Update Last Build Date

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # This is crucial for push access

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update timestamp
        run: |
          sed -i "s/<div class=\"version-inline-below\" id=\"lastUpdate\">.*<\/div>/<div class=\"version-inline-below\" id=\"lastUpdate\">Last Updated: $(date -u '+%Y-%m-%d %H:%M %Z')<\/div>/" nepal-salary-tax-calculator/index.html
      
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add nepal-salary-tax-calculator/index.html
          git commit -m "Auto-update last modified date [skip ci]" || echo "No changes to commit"
          git push