name: Update Last Modified Date

on:
  push:
    branches: [ main ] # or your branch name

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      name: Clean old files
      run: rm -rf tax-calculator/ || true
  
      - name: Update timestamp
        run: |
          sed -i "s/<div class=\"version-inline-below\" id=\"lastUpdate\">.*<\/div>/<div class=\"version-inline-below\" id=\"lastUpdate\">Last Updated: $(date -u '+%Y-%m-%d %H:%M %Z')<\/div>/" tax-calculator/index.html
      
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add nepal-salary-tax-calculator/index.html
          git commit -m "Auto-update last modified date" || echo "No changes to commit"
          git push